language: objective-c
osx_image: xcode7.3
env:
  global:
  - PROJECT="Interact with Keyboard.xcodeproj"
  - SCHEME="Interact with Keyboard"
  - DESTINATION="OS=9.3,name=iPhone 6S Plus"
  - IOS_SDK="iphonesimulator9.3"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c
